name: Build and Deploy

on:
  workflow_dispatch:
  # Uncomment the following lines to enable the workflow on push to the main branch
  # push:
  #   branches: [ "main" ]

jobs:
  build:
    uses: harold-barron/actions/.github/workflows/build_Node.yaml@main
    with:
      package-path: .

  
